### ISSUE TITLE
Full Stack project review

### ISSUE THREAD

**Issue by Kaltsoon** [hpkhanhloc/loc-hoang-webpage#22]
# Full Stack project review

Hi @hpkhanhloc! Here's a short code review for your Full Stack course project. The comments in this review are just suggestions for improvements, which you can take into account in this or in the future projects, _if you want to_. You don't have to do any changes in this project based on these comments to get the credits. 

### What did I do?

- Signed up
- Checked my user info and edited my profile
- Went through the pages
- Logged out
- Logged in with a user with the owner rights
- Checked the functionality with owner rights
- Logged out

### Experience

- The application's user interface is very user friendly and stylish. Good job! 🚀
- Switching between the light and the dark theme is a really cool feature
- User with owner rights doesn't seem to be able to make edits in the home page (I got "Create content failed: FirebaseError: [code=permission-denied]: Missing or insufficient permissions."). If this is intentional, perhaps these buttons shouldn't be visible

## Code

- The front-end code is well organized, great work!
- Consider using `const` type variables for storing action types instead of using hard coded [strings](https://github.com/hpkhanhloc/loc-hoang-webpage/blob/master/frontend/src/actions/alertActions.js#L4). This minimizes the risk of bugs caused by typos and eases refactoring. Redux's documentation has great [instructions](https://redux.js.org/basics/actions) regarding this
- You should use [action creators](https://redux.js.org/basics/actions#action-creators) instead of [plain objects](https://github.com/hpkhanhloc/loc-hoang-webpage/blob/master/frontend/src/actions/alertActions.js#L16) when dispatching actions. When you abstract the creation of the action with an action creator it is much easier to change the underlying structure and logic later without a need of major refactoring.
- [Redux Toolkit](https://redux-toolkit.js.org/) has great functionality for reducing Redux boilerplate code for example when defining action creators
- [useTimer](https://github.com/hpkhanhloc/loc-hoang-webpage/blob/master/frontend/src/hooks/useTimer.js) is a great custom hook. Perhaps you could create more custom hooks. For example [here](https://github.com/hpkhanhloc/loc-hoang-webpage/blob/master/frontend/src/components/Blogs.js#L20) a `useBlogs` hook would simplify the component's code
- A form state management library such as [Formik](https://formik.org) makes it easier to handle the state of larger forms

## Summary

Execellent personal website, which looks and feels very professional! The user interface is very stylish and easy to use. The code is well organized and mostly pretty high quality. Good job!

**Comment by hpkhanhloc** [comment]
> User with owner rights doesn't seem to be able to make edits in the home page (I got "Create content failed: FirebaseError: [code=permission-denied]: Missing or insufficient permissions."). If this is intentional, perhaps these buttons shouldn't be visible

That's true, only my account with matched UID can edit it. It is my intentional, only the highest user have right to edit home page.

I'm still developing the website, and will combine with some other projects also ( such as my thesis if possible), therefore your suggestion is really useful for me.
I really appreciate and thank for your assessment!

**Comment by Kaltsoon** [comment]
Great, keep up the good work! :)
